os: linux
sudo: required
dist: trusty

notifications:
  email: false

branches:
  only:
    - travis-ci

language: C++

before_install:
  - sudo apt-get install gfortran
  - wget https://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-2.1.1.tar.gz
  - tar xvf openmpi-2.1.1.tar.gz
  - cd openmpi-2.1.1
  - ./configure >/dev/null 2>&1
  - make >/dev/null 2>&1
  - sudo make install >/dev/null 2>&1
  - cd ../
  - sudo ldconfig
  - sudo apt-get install python-dev
  - sudo apt-get install doxygen
  - sudo apt-get install cmake
  - wget https://downloads.sourceforge.net/swig/swig-3.0.12.tar.gz
  - tar xvf swig-3.0.12.tar.gz
  - cd swig-3.0.12
  - ./configure >/dev/null 2>&1
  - make >/dev/null 2>&1
  - sudo make install >/dev/null 2>&1
  - cd ../
  - sudo pip install scipy --upgrade
  - sudo pip install numpy --upgrade
  - sudo pip install mpi4py --upgrade
  - test -n $CC  && unset CC
  - test -n $FCC  && unset FCC
  - test -n $CXX && unset CXX
  - mkdir build

script:
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=../Targets/Linux.cmake ..
  - make
  - make test > test_result.txt
  - tail Testing/Temporary/LastTest.log
